### ISSUE TITLE
fail tests if formatting required

### ISSUE THREAD

**Issue by fommil** [sbt/sbt-scalariform#18]
is it possible to set up compile and tests to fail if anything needs to be reformatted?

I'd like to strictly enforce a formatting criteria on pull request acceptance.

**Comment by slomo** [comment]
Are there any plans to support this feature or would a pull request have a chance for acceptance?

**Comment by fommil** [comment]
see #20 for who to contact for this project. Ownership is a bit confused at the moment.

**Comment by blrnw3** [comment]
👍 this would be very handy
