### ISSUE TITLE
use maintained version of scalariform

### ISSUE THREAD

**Issue by fommil** [sbt/sbt-scalariform#20]
the canonical source of scalariform appears to have rotted, but work appears to be ongoing at https://github.com/daniel-trinh/scalariform

http://search.maven.org/#search%7Cga%7C2%7Cscalariform

It would be good if this sbt plugin used that newer version.

**Comment by fommil** [comment]
@hseeberger at ensime we're quite badly effected by the zombied state of scalariform: https://github.com/ensime/ensime-server/issues/792

@mdr has tentatively agreed to give publishing rights to `org.scalariform` to @daniel-trinh but nothing has come of it.

Daniel has created an updated version of his fork of scalariform (and the sbt plugin, I think) which use a new FQN namespace for his version, so that use of both `org.scalariform` and `com.danieltrinh` doesn't blow up the 

Do you have publishing rights to `org.scalariform` by any chance? Would you consider merging in daniel's changes to the sbt plugin so that we can all at least get into one version of the plugin?

Otherwise, in ensime, we have to support all the variants as if they are separate libraries, which is **not** fun.

**Comment by fommil** [comment]
I'm just seeing that this uses `com.typesafe.sbt`. OK, well in that case, would you consider merging the changes from daniel's fork?

**Comment by hseeberger** [comment]
Adding our sbt Grand Wizard @jsuereth to this thread ...

**Comment by ktoso** [comment]
@daniel-trinh has taken over development and has also been given credentials to release under the same good-old group-id / artifact-id :-) In fact, there's been a new release! https://github.com/daniel-trinh/scalariform/releases/tag/0.1.6

It includes a feature which makes formatting complex akka-streams code more readable ( https://github.com/daniel-trinh/scalariform/issues/45 ) so would be great to update to it.

**Comment by fommil** [comment]
Yes, I know, I asked him to do it ;-)

**Comment by fommil** [comment]
Actually, he's publishing his fork to this group and artefact. The most sensible thing would be to add him as a contributor/ admin on this repo.

**Comment by fommil** [comment]
uuuugggh, I've just realised that we now have a **THIRD** group name in the mix now

* com.typesafe.sbt
* org.scalariform
* com.danieltrinh

I recommend that `org.scalariform` be the official groupId and that the other two are dummy packages that simply depend on it.

Otherwise we get nightmare classpath problems, where the jar actually used in the project is randomly selected from all the plugins pulled in by the user, or transitively by plugins.

**Comment by hseeberger** [comment]
I agree. On the long run there should only be one (Highlander principle) and IMHO that should be org.scalariform. I think it's just a matter of someone stepping up and doing what needs to be done. @daniel-trinh?

**Comment by hseeberger** [comment]
If that doesn't happen soon, I'll create a 4th solution (de.heikoseeberger) based on Scala Meta ;-)

**Comment by ktoso** [comment]
The reason I pinged this issue again is that Daniel now released `1.6` under `org.scalariform` to maven central ( http://search.maven.org/#search|ga|1|org.scalariform ) - so I thought it's a good point in time to nudge all projects to moving to depending on that one :-)

**Comment by fommil** [comment]
it would help a lot if a scalariform group were set up on github, with @daniel-trinh / @hseeberger  / @mdr as admins. It would be ideal if mdr could then give ownership of the scalariform repo to that group, and @sbt give ownership of the plugin to that group (they can both fork the repo back into their own spaces again). This is what we did in ensime when it became bigger than one person... it means all forks lead back to the one true Highlander :wink:

**Comment by fommil** [comment]
but yes, tangential to that... the "slain highlanders" all need to have pom-only artefacts pushed out that depend on the highlander.

**Comment by fommil** [comment]
all ! Ping

This is the live and latest version of sbt-scalariform:

```scala
addSbtPlugin("org.scalariform" % "sbt-scalariform" % "1.4.0")
```

please turn your published artefact into a pom and simply depend on it, or talk to @daniel-trinh and decide who is responsible for maintaining the sbt-scalariform going forward.

**Comment by crypticmind** [comment]
I just tried `"org.scalariform" % "sbt-scalariform" % "1.4.0"` and seems to be working OK.
If this version can be considered golden, could you please update this project's [README](https://github.com/sbt/sbt-scalariform/blob/master/README.md)? The instructions there still refer people to the old version.

**Comment by bleadof** [comment]
Did a PR #25 to change the README

**Comment by fommil** [comment]
latest on this is that Matt Russell gave the keys of scalariform to @sschaef and both myself and @daniel-trinh have been added with write access / review rights. It would make sense for Simon to also be added to this repo and be given sonatype access so that both him/Daniel (whoever is nearest the keyboard) can make releases under the groupId used here.

**Comment by eed3si9n** [comment]
There was a pull request to merge @daniel-trinh's fork (#28), so I've merged it over the break (12 days ago). I've also took the liberty of purchasing http://scalariform.org/ (you need to own the domain name to use it on Sonatype or sbt community repo), so if there's a Github site someone wants to make we can point at it.

**Comment by fommil** [comment]
Cool! I guess the question is which groupId do we use?

**Comment by eed3si9n** [comment]
@fommil I've created [sbt-scalariform team](https://github.com/orgs/sbt/teams/sbt-scalariform) with the admin right to this repo and invited you, Daniel, and Simon.

My opinion is:

- Use `org.scalariform` GroupID for both the library and the sbt plugin.
- Publish library to Sonatype OSS
- Publish sbt plugin to sbt community repo

**Comment by sschaef** [comment]
What is sbt community repo?

**Comment by fommil** [comment]
Simon is working on reconciling the forked repo, if I had any spare cycles I'd like to help set up some integration tests, but I think it's probably best that Simon does not. There are a few outstanding tickets on Daniel's sbt-scalariform. We should probably migrate those here ((and any outstanding PRs) then close the tracker.

**Comment by eed3si9n** [comment]
- http://www.scala-sbt.org/0.13/docs/Community-Plugins.html#Community+Ivy+Repository
- http://www.scala-sbt.org/0.13/docs/Bintray-For-Plugins.html

It's basically https://bintray.com/sbt/sbt-plugin-releases + https://repo.scala-sbt.org/

**Comment by fommil** [comment]
Does **that**. Damned autocorrect!

**Comment by fommil** [comment]
Eugene's plan sounds good. It would be good to publish ivy/pom only updates for the other two groupIds that simply pull it this version to avoid nasty classpath problems.

**Comment by dwijnand** [comment]
This issue is either done and should be closed (seeing as this is now sbt/sbt-scalariform), or it should be re-titled for the follow-up work Sam described. (Personally I don't like re-purposing tickets).
