### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by 99sono** [sbt/sbt-scalariform#23]
Hi,

I am wondering if continued improvements for the netbeans sbt plugin are essentially dead / stopped for the time being?

The Eclipse IDE development and SBT plugin seems to be actively on-going, while netbeans sbt support seem to be practically non existent. It has been more than an year since this git project has seen a release.

Personally, i quite prefer Netbeans. For Java development alonside with Maven the IDE is in my opinion light years better than eclipse. I was hoping for something similar for Netebeans alonside SBT. The same philosophy of let SBT work on the build, execution and testing and Netbeans focusing on helping you develop with this build tool.

However,  at this point in time, SBT + Netebeans simply does not work properly, you have to use either Netebeans + Maven for scala projects (which works actually quite well) or go for  Eclipse IDE, that is unfortunately quite quite superior at this point time.

Thanks for any information on this regard.

**Comment by jozic** [comment]
@eed3si9n  @jsuereth 
should this be deprecated in favor of https://github.com/daniel-trinh/sbt-scalariform?

**Comment by metasim** [comment]
@jozic: As a lurker, I poked around a bit, and don't see where @daniel-trinh has submitted a pull request, although @yeghishe has one pending. There's definitely been some divergence. I'd be interested in hearing from @daniel-trinh to know if he has plans to submit a PR, and from @eed3si9n as to how we might consolidate efforts.


![screen shot 2015-10-13 at 9 28 20 pm](https://cloud.githubusercontent.com/assets/131013/10472711/9434e2dc-71f1-11e5-910d-b4c323d44d13.png)

**Comment by metasim** [comment]
PS: I think the title of this issue should be changed to reflect some actionable task.

**Comment by daniel-trinh** [comment]
Submitting a MR to merge my branch into this is on my list of things to do, although I am considering fixing a few bugs in relation to backwards compatibility before I get to doing that.

**Comment by eed3si9n** [comment]
I've already given the control of this project @daniel-trinh around a month ago with the blessing of Heiko.
sbt/sbt-scalariform hopefully lives on as the definitive repo.

**Comment by metasim** [comment]
@daniel-trinh @eed3si9n Great news on both fronts!
