### ISSUE TITLE
Is this project superceded by daniel-trinh project?

### ISSUE THREAD

**Issue by ms-ati** [sbt/sbt-scalariform#29]
Hi all,

Is this project superceded by https://github.com/daniel-trinh/sbt-scalariform ?

If so, would you mind explaining that in the README, so that people don't think scalariform is dead?

**Comment by eed3si9n** [comment]
The plan is to let Daniel become the maintainer of this one. See https://github.com/sbt/sbt-scalariform/pull/28.

**Comment by ms-ati** [comment]
Ah! Ok, thanks Eugene.

**Comment by fommil** [comment]
dupe of #20

**Comment by fommil** [comment]
watch this space :smile:
