### ISSUE TITLE
Cannot see git tag for latest 1.6.0 release

### ISSUE THREAD

**Issue by dinoboy197** [sbt/sbt-scalariform#34]
I'm trying to find the Git tag for the latest 1.6.0 release, but I can't find it in this project. Would you mind pushing that tag up to Github, please?

**Comment by fommil** [comment]
good point, @sschaef looks like all the tags from daniel's repo are missing

**Comment by sschaef** [comment]
Daniels fork doesn't have a 1.6.0 tag nor any other new tags. There are new branches however but I don't know if they can be seen as absolute references. @daniel-trinh Could you please create the tags or push them upstream if you have them in your repo?

**Comment by daniel-trinh** [comment]
@sschaef Master is the equivalent of 1.6.0 at the moment, I just pushed a git tag for it.

**Comment by daniel-trinh** [comment]
Actually, I suppose I pushed a branch, not a git tag. Do we need git tags for the previous releases?

 Feel free to push an actual git tag if I don't get around to it.

**Comment by dinoboy197** [comment]
The reason that I was asking for tags is that it's important for me to be able to view the exact code & commits before using a new version. Without that I'm typically hesitant to upgrade in my organization's projects (and we use sbt-scalariform in *many* projects). (Note that this isn't for just sbt-scalariform but all open-source libraries that we use.) Without tags (or other explicit shas in the README), it's hard to know which commits exactly were used in creating which releases.

**Comment by fommil** [comment]
thanks for creating those tags, @daniel-trinh !

**Comment by lunaryorn** [comment]
I'm sorry, maybe I'm missing something, but I see no recent tags in repository.  There are branches, but no tags.

Would you mind to add tags as well? They play better with Github, specifically tags can be followed with RSS feeds to get notified on new versions.

**Comment by fommil** [comment]
@lunaryorn he never created them. It would be good to have them retrospectively.

**Comment by godenji** [comment]
Tags for 1.4 and 1.6 were added after the fact (on [April 16, 2017](https://github.com/sbt/sbt-scalariform/tags))
