### ISSUE TITLE
Update scalariform version to `0.2.0`

### ISSUE THREAD

**Issue by jvican** [sbt/sbt-scalariform#36]
It would be awesome if you can update the version of scalariform as they have added new configuration settings like `doubleInsideDeclarationMethod`.

Also, I would appreciate if you can publish it.

**Comment by ryan-williams** [comment]
Is scalariform 0.2.0 released? I don't see it anywhere, e.g. http://search.maven.org/#search%7Cga%7C2%7Cscalariform

**Comment by MrPowers** [comment]
@ryan-williams - You can find the scalariform 0.2.0 snapshot [here](https://oss.sonatype.org/content/repositories/snapshots/org/scalariform/scalariform_2.11/0.2.0-SNAPSHOT/).

@sschaef [sent me this on Reddit](https://www.reddit.com/r/scala/comments/60tygk/scalariform_needs_a_new_maintainer/dftdavz/).

I'd be awesome if the current Scalariform repo could be tagged with a release and then the JAR file could be uploaded to an easy location for @ryan-williams to update sbt-scalariform.

**Comment by godenji** [comment]
1.7.0 published with dependency on scalariform 0.2.1
