### ISSUE TITLE
firstArgumentOnNewline setting is missing

### ISSUE THREAD

**Issue by dskrvk** [sbt/sbt-scalariform#45]
Or does it have a different name? Couldn't find it in `scalariform.formatter.preferences`.

See https://github.com/scala-ide/scalariform#firstargumentonnewline

**Comment by ryan-williams** [comment]
It seems like it didn't exist as a configurable setting in scalariform as of 0.1.8 (the latest release): https://github.com/scala-ide/scalariform/tree/0.1.8. 

We'll have to wait on a new scalariform release and then a release here that uses it, I guess?

**Comment by godenji** [comment]
Setting is available in `sbt-scalariform` 1.7.0
