### ISSUE TITLE
Run with only a white-list of preferences

### ISSUE THREAD

**Issue by ryan-williams** [sbt/sbt-scalariform#52]
I'd like to only apply the `SpacesAroundMultiImports` changes to my code, but I get a bunch of other changes I've not opted in to when I run using `sbt scalariformFormat`.

Is there a way to disable all preferences except for one or a few that I want to apply?

Currently I get noisy changes I don't want like:

```scala
-  def hasMaximumMedianMismatch(somaticGenotype: CalledSomaticAllele,
-                               maximumMedianMismatches: Int): Boolean = {
+  def hasMaximumMedianMismatch(
+    somaticGenotype: CalledSomaticAllele,
+    maximumMedianMismatches: Int
+  ): Boolean = {
```

**Comment by godenji** [comment]
file an issue on scalariform, sbt-scalariform has no control over which settings are applied (i.e. either settings are user defined or fallback to setting defaults)
