### ISSUE TITLE
upgrade sbt to 0.13.12 with settings that avoid complete reformat of project

### ISSUE THREAD

**Issue by noahlz** [sbt/sbt-scalariform#54]
I have several projects that use an earlier version of sbt (0.13.5). When I upgrade to 0.13.12+, the scalariform version changes, and the project gets completely reformatted.

salat/salat#169

Apparently formatting rules (with regards to whitespace, parameters on new line vs. same line, etc.) changed between scalariform versions - which changes with the new sbt version.

However, I don't want to reformat my entire project. I like the current formatting the projects have, with the old rules. Also, just accepting the new formatting and committing them to the project would create a lot of noise in the revision history, and conflicts with PRs between old vs. newer branches.

Is there an easy way to upgrade to a newer version of sbt, and thus the Scalariform plugin, but maintain the "legacy" formatting rules?  Is there an migration guide between 0.13.5 and 0.13.12+ for the sbt-scalariform and its configuration?

**Comment by godenji** [comment]
Your best bet is to experiment with the latest release (1.7.0) and see if currently available settings can replicate existing formatting in projects that depend on older versions of scalariform.

See the scalariform [reference.conf](https://github.com/scala-ide/scalariform/blob/master/formatterPreferences.properties) for available settings and their defaults. These are the settings against which scalariform itself is formatted.
