### ISSUE TITLE
Update the plugin to use the 0.2.0-SNAPSHOT scalariform version

### ISSUE THREAD

**Issue by MrPowers** [sbt/sbt-scalariform#55]
@sschaef provided a link to this snapshot in [this Reddit thread](https://www.reddit.com/r/scala/comments/60tygk/scalariform_needs_a_new_maintainer/dftdavz/).

I'd really love for sbt-scalariform to be in sync with all of the preferences in [the current scalariform README](https://github.com/scala-ide/scalariform#preferences).

You'll need [to change some code](https://github.com/sbt/sbt-scalariform/blob/76d65f56a66c75e37dc9ae50059aa7468b21559a/build.sbt#L32-L41), but it shouldn't be too bad.  There's not too much to change.

Let me know if I can help if any way!

**Comment by MrPowers** [comment]
There is [another 0.2.0 version here](https://mvnrepository.com/artifact/com.github.machaval/scalariform_2.12) from [this Redditor](https://www.reddit.com/r/scala/comments/60tygk/scalariform_needs_a_new_maintainer/dg979q6/).

**Comment by godenji** [comment]
sbt-scalariform 1.7 was just published (should be on Maven Central shortly), it depends on scalariform 0.2.1.
