### ISSUE TITLE
sbt 1.0.0 support

### ISSUE THREAD

**Issue by pjfanning** [sbt/sbt-scalariform#64]
I tried the latest release in sbt 1.0 but I'm getting an error.
addSbtPlugin("com.typesafe.sbt" % "sbt-scalariform" % "1.7.1")

There doesn't appear to be a scala 2.12 release in https://dl.bintray.com/sbt/sbt-plugin-releases/com.typesafe.sbt/sbt-scalariform/

Is there a plan to release an sbt 1.0 compatible release or is there an alternative plugin you could recommend?

**Comment by godenji** [comment]
use `1.8.0`, it's up on Maven Central as of yesterday -- haven't published github release yet, nor, as you've noticed, updated the readme ;-)

**Comment by pjfanning** [comment]
@godenji thanks

**Comment by raisercostin** [comment]
Isn't it addSbtPlugin("org.scalariform" % "sbt-scalariform" % "1.8.2")? Like the one available at https://repo1.maven.org/maven2/org/scalariform/sbt-scalariform_2.10_0.13/1.8.2/ ?
