### ISSUE TITLE
Automatically exclude Play routes files from formatting

### ISSUE THREAD

**Issue by balagez** [sbt/sbt-scalariform#71]
Reopening https://github.com/sbt/sbt-scalariform/issues/32 which was fixed in 1.7.1 but it's now broken again in 1.8.0

**Comment by balagez** [comment]
Cause is probably the changes introduced in https://github.com/sbt/sbt-scalariform/commit/42ca0f04b5e7280afcf8eec896580f141be85891

**Comment by godenji** [comment]
@balagez fix is in 1.8.1 release
