### ISSUE TITLE
Unable to set formatting preferences for sub-project

### ISSUE THREAD

**Issue by 2m** [sbt/sbt-scalariform#72]
When using 1.8.0 it is unable to set a different formatting preferences for the sub-project. The root project formatting preferences are being used when formatting code in all of the projects.

**Comment by jroper** [comment]
Not 100% sure, but it's possible that #75 fixes this.

**Comment by godenji** [comment]
@2m please try the 1.8.1 release.

**Comment by 2m** [comment]
Yes. It works now. Thanks!
