### ISSUE TITLE
Scalariform formatting sourceDirectories handling is wrong (esp. in multiproject builds)

### ISSUE THREAD

**Issue by simlei** [sbt/sbt-scalariform#73]
Originally a followup in https://github.com/sbt/sbt-scalariform/issues/40#issuecomment-332893123

In the past year, source folder inclusion in this plugin seems to have seen quite a few changes. The last one made a huge dent in the performance of building my project (10+ subprojects) because it made Scalariform format each file in that build as many times as there are subprojects. That hurt - I'm just gonna past the followup here again. Plugin admin suggested as much in the original thread.It also contains the argument + context that triggered the last change.

Each subproject's ``scalariformFormat`` task in their different scopes have the project root in their ``sourceDirectories`` setting. This just leads to the whole project being crawled for scala sources and formatted as many times as there are subprojects. 

Caching __seems__ to do nothing for me - maybe the cache resides in the subproject folders? In any case, it produces such output when compiling:
```
[info] Formatting 1449 Scala sources {file:/home/simon/git/opal_hiwi/}BytecodeRepresentation(compile) ...
[info] Reformatted 1 Scala source {file:/home/simon/git/opal_hiwi/}BytecodeRepresentation(compile).
[info] Formatting 1449 Scala sources {file:/home/simon/git/opal_hiwi/}BytecodeInfrastructure(compile) ...
[info] Formatting 1449 Scala sources {file:/home/simon/git/opal_hiwi/}Incubation(compile) ...
[...]
```

It should be noted that in my setup, sbt-scalariform is not configured for the aggregating root project, just for the subprojects. 

IMHO the ``sourceDirectories`` setting should just include the subproject root, not the "real" root. In extension, the current behavior just causes each and every file that "just" matches the filters in a subproject to be formatted, regardless of its path - it searches the root **recursively** in the current mode of configuration. I am not sure this is expected behavior.

This is the code that's responsible:

https://github.com/sbt/sbt-scalariform/blob/3b83dbe29f739ec593769dda19810ba6a3b6e751/src/main/scala/com/typesafe/sbt/SbtScalariform.scala#L100-L103

For a basic fix (not breaking subproject scopes and forced redundant formatting) it would require to change this line: https://github.com/sbt/sbt-scalariform/blob/3b83dbe29f739ec593769dda19810ba6a3b6e751/src/main/scala/com/typesafe/sbt/SbtScalariform.scala#L102

by replacing ``LocalRootProject`` with ``ThisProject``.

An even more meaningful change i think would be to treat the local (sub-)project root differently from the other source directories, or plainly ignore them. Nowhere in the Scala spec is written that sources may reside in the root folder **and** its subfolders, just the root folder (and this smells like a concession to make "helloworld" projects easier). Even though, in 

https://github.com/sbt/sbt-scalariform/blob/3b83dbe29f739ec593769dda19810ba6a3b6e751/src/main/scala/com/typesafe/sbt/Scalariform.scala#L61

among others, the root folder **will** be filtered recursively for source files. To change this, the code managing targets for formatting must somewhere navigating this disjunction between 2 types of source inclusion. Here's how ensime handles that: https://github.com/ensime/ensime-server/issues/1432: Ignoring this special case.

If there is agreement I can make a PR.

For anyone interested in a workaround, I am currently using this to configure subprojects in the root/build.sbt:

```
lazy val scalariformSettings = scalariformSettingsWithIt(true) ++
	Seq(ScalariformKeys.preferences := baseDirectory(getScalariformPreferences).value) ++
	Seq(sourceDirectories.in(Compile, ScalariformKeys.format) -= baseDirectory.in(LocalRootProject).value) ++
	Seq(sourceDirectories.in(Test, ScalariformKeys.format) -= baseDirectory.in(LocalRootProject).value) ++
	Seq(sourceDirectories.in(IntegrationTest, ScalariformKeys.format) -= baseDirectory.in(LocalRootProject).value)
```

**Comment by evanbennett** [comment]
With regards to `baseDirectory` being in `sourceDirectories in scalariformFormat`:
* I would like to suggest reviewing the `sourcesInBase` setting, which I personally set to false.
* Also, if you review `unmanagedSources` and `unmanagedSourceDirectories` in https://github.com/sbt/sbt/blob/1.x/main/src/main/scala/sbt/Defaults.scala, `unmanagedSources` gets descendants (recursively) of `unmanagedSourceDirectories`, but gets children (non-recursively) of `baseDirectory`.

To handle this would probably require changing `Scalariform.apply` to take `sourceFiles` rather than `sourceDirectories`, `includeFilter` and `excludeFilter`, and moving gathering the files to `SbtScalariform`.

**Comment by godenji** [comment]
@simlei @evanbennett please try the 1.8.1 release -- base directory is now opt-in

**Comment by simlei** [comment]
Nice, thanks for the update. That seems to solve the issue for my project.
